### ISSUE TITLE
Casing question for repo titles

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAS-Best-Practices#1]
Just a note that casing seems to matter for GH pages by default.  There might be workarounds for this, but since URLs are case sensitive, perhaps we should go with a lower-case names for any repos that will include web pages?    

Examples:
- https://saa-sdt.github.io/EAS-Best-Practices/ (works)
- https://saa-sdt.github.io/eas-best-practices/ (does not work)

I'm not sure if we should have a rule or not that acronyms are always capitalized, but this is a good reason to not adopt that rule perhaps :) 

Note, however, that it does look like GH will provide re-directs for file URLs and its own pages, e.g. in the "EAD3" repo:

- https://raw.githubusercontent.com/SAA-SDT/EAD3/master/ead3.rng (works)
- https://raw.githubusercontent.com/SAA-SDT/ead3/master/ead3.rng (also works)

**Comment by karinbredenberg** [comment]
I would go for one type of casing and since we havent promoted or filled this repository yet make the change as soon as possible.

**Comment by kerstarno** [comment]
Agree with Karin: one type of casing (i.e. either all small letters or with capitalisation for acronyms and the start of any nouns). Plus, if the name consists of several terms, use hyphen between the terms for readability. 

That being said: it looks like the capitalised URLs are generally working better?

**Comment by fordmadox** [comment]
We're keeping things as is and not worrying about the case sensitivity.
